changelog:
  exclude:
    labels:
      - chore
  categories:
    - title: Breaking Changes 🛠
      labels:
        - major
    - title: Exciting New Features 🎉
      labels:
        - minor
    - title: Fixes
      labels:
        - patch
