name: Container vulnerability scan
on:
  workflow_call:
    inputs:
      image:
        type: string
        description: Container image name and tag to scan
        required: true
      login_dockerhub:
        type: boolean
        description: "Login to DockerHub, requires the secrets DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD (default: false)"
        reguired: false
        default: false
      trivy_tag:
        type: string
        description: "Use a special aquasec/trivy container image tag (default: latest)"
        required: false
        default: latest
    secrets:
      DOCKERHUB_USERNAME:
        description: "The username to login to Docker Registry."
        required: false
      DOCKERHUB_PASSWORD:
        description: "The password to login to Docker Registry."
        required: false
jobs:
  vulnerability-scan:
    name: Container vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub container registry
        if: ${{ inputs.login_dockerhub }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Pull aquasec/trivy
        run: |
          docker pull aquasec/trivy:${{ inputs.trivy_tag }}
      - name: Vulnerability scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:${{ inputs.trivy_tag }} -q image ${{ inputs.image }} | tee -a ${GITHUB_STEP_SUMMARY}
