name: Container vulnerability scan
description: Vulnerability scan of container images using aquasec/trivy
inputs:
  image:
    description: Container image name and tag to scan
    required: true
  login_dockerhub:
    description: "Login to DockerHub, requires seceets DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD (default: false)"
    reguired: false
    default: false
  trivy_tag:
    description: "Use a special aquasec/trivy container image tag (default: latest)"
    required: false
    default: latest
on:
  workflow_call:
jobs:
  vulnerability-scan:
    name: Container vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub container registry
        if: ${{ inputs.login_dockerhub }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Pull aquasec/trivy
        run: |
          docker pull aquasec/trivy:${{ inputs.trivy_tag }}
      - name: Vulnerability scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:${{ inputs.trivy_tag }} -q image ${{ inputs.image }} | tee -a ${GITHUB_STEP_SUMMARY}
